### ISSUE TITLE
monzo_spend_today should be a counter

### ISSUE THREAD

**Issue by philandstuff** [tlwr/monzo-exporter#2]
`monzo_spend_today` looks like a candidate for a counter, except that it should be `monzo_spend_total` which counts up total outgoings since exporter process start.  This means:

 -  you can use PromQL to compute total spend over arbitrary periods (eg `increase(monzo_spend_total[3w]`)

You could use a Counter with the [Add()](https://github.com/prometheus/client_golang/blob/master/prometheus/counter.go#L87) method to increment the counter.

**Comment by tlwr** [comment]
As currently implemented this reports the current value of `spend_today` from the [Monzo API Read Balance endpoint](https://docs.monzo.com/#balance). This value appears to be able to mutate depending on if transactions are refunded.

This seems like a good suggestion to add `monzo_spend_total` as a counter to accompany the current gauge.

**Comment by philandstuff** [comment]
:thinking: hmm, if it can go down as well as up with refunds, i think it's just a gauge. also I don't think it's the exporter's job to create things like `monzo_spend_total` - that's better suited to a [recording rule](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/). Closing (because I think it's not needed) but feel free to reopen if you think it's worthwhile.
